"""CAD-based screening of the two SAND2013-2569 sandwich shear webs.

The applied spanwise shear is the numerical derivative of the already factored
parked-fault bending-moment envelope. It is shared equally by the two webs.
Web height comes from ``cad_web_geometry.csv`` generated by FreeCAD.

Global shear buckling uses the simply-supported long-plate screening form
Nxy_cr = k_s*pi^2*sqrt(D11*D22)/h^2, k_s=5.34+4/(a/h)^2.
This is deliberately a screening equation; curvature, adhesive flanges and
shell restraint require shell FEA and are not credited.
"""

from __future__ import annotations

import csv
from pathlib import Path
import sys

WIND_WING_ROOT = Path(__file__).resolve().parents[3]
COMPOSITES_ROOT = WIND_WING_ROOT.parent / "Composites_physics"
if str(COMPOSITES_ROOT) not in sys.path:
    sys.path.insert(0, str(COMPOSITES_ROOT))

import numpy as np

from laminate import assemble_laminate_stiffness


SESSION_ROOT = Path(__file__).resolve().parents[1]
CAD_CSV = SESSION_ROOT / "results" / "cad_web_geometry.csv"
LOAD_CSV = WIND_WING_ROOT / "results" / "structural" / "glass_station_results.csv"
OUT = SESSION_ROOT / "results"

FACE = {"E1": 13.6e9, "E2": 13.3e9, "G12": 11.8e9, "v12": 0.49}
CORE = {"E1": 256e6, "E2": 256e6, "G12": 22e6, "v12": 0.30}
FACE_T_M = 0.002       # 2 x 1 mm Saertex DB, SAND2013-2569 Tables 5 and 13
CORE_T_M = 0.050       # SAND2013-2569 Table 13
FACE_UCS_PA = 213e6    # SAND2013-2569 Table 5
FACE_SHEAR_PA = 62e6   # project material DB, MAT-001/MAT-002 cross-check
CORE_SHEAR_PA = 1.8e6  # DIAB Divinycell H100, MAT-006; conservative proxy
ASPECT_RATIOS = np.linspace(0.5, 10.0, 191)


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        return [row for row in csv.DictReader(
            line for line in handle if not line.lstrip().startswith("#")
        )]


def web_stiffness(face_t_m: float = FACE_T_M):
    layup = [
        {"theta": 0.0, "t": face_t_m, "mat": 0},
        {"theta": 0.0, "t": CORE_T_M, "mat": 1},
        {"theta": 0.0, "t": face_t_m, "mat": 0},
    ]
    return assemble_laminate_stiffness(layup, [FACE, CORE])


def shear_buckling_N_per_m(height_m: float, a_over_h: float, face_t_m: float = FACE_T_M) -> float:
    if height_m <= 0 or a_over_h <= 0:
        raise ValueError("height_m and a_over_h must be positive")
    d = web_stiffness(face_t_m).D
    k_s = 5.34 + 4.0 / a_over_h**2
    return float(k_s * np.pi**2 * np.sqrt(d[0, 0] * d[1, 1]) / height_m**2)


def face_wrinkling_stress_Pa() -> float:
    return float(0.5 * (CORE["G12"] * CORE["E2"] * FACE["E1"]) ** (1.0 / 3.0))


def load_shear_schedule() -> tuple[np.ndarray, np.ndarray]:
    rows = read_rows(LOAD_CSV)
    r = np.array([float(row["r_m"]) for row in rows])
    m = np.array([float(row["M_park_fault_design_Nm"]) for row in rows])
    # V = |dM/dr|. The input moment already contains the parked-fault design factor.
    return r, np.abs(np.gradient(m, r, edge_order=2))


def assess(
    face_layers: int = 2,
    reinforced_span: tuple[float, float] | None = None,
) -> tuple[list[dict[str, object]], list[dict[str, object]], list[dict[str, object]]]:
    cad = read_rows(CAD_CSV)
    load_r, shear = load_shear_schedule()
    summary = []
    sweep = []
    demand = []
    wrinkle = face_wrinkling_stress_Pa()

    for row in cad:
        r = float(row["blade_span_m"])
        h = float(row["web_height_m"])
        active_layers = face_layers
        if reinforced_span is not None and not (reinforced_span[0] <= r <= reinforced_span[1]):
            active_layers = 2
        face_t = active_layers * 0.001
        a66 = 2.0 * FACE["G12"] * face_t + CORE["G12"] * CORE_T_M
        total_v = float(np.interp(r, load_r, shear))
        web_v = total_v / 2.0
        applied_nxy = web_v / h
        gamma = applied_nxy / a66
        face_tau = FACE["G12"] * gamma
        core_tau = CORE["G12"] * gamma
        core_rf = CORE_SHEAR_PA / core_tau if core_tau > 0 else float("inf")
        face_shear_rf = FACE_SHEAR_PA / face_tau if face_tau > 0 else float("inf")
        face_wrinkling_rf = wrinkle / face_tau if face_tau > 0 else float("inf")
        face_compression_rf = FACE_UCS_PA / face_tau if face_tau > 0 else float("inf")
        station_sweep = []
        for ratio in ASPECT_RATIOS:
            ncr = shear_buckling_N_per_m(h, float(ratio), face_t)
            rf = ncr / applied_nxy if applied_nxy > 0 else float("inf")
            item = {
                "blade_span_m": r, "web": row["web"], "face_layers_each_side": active_layers,
                "a_over_h": float(ratio),
                "web_height_m": h, "applied_Nxy_N_per_m": applied_nxy,
                "critical_Nxy_N_per_m": ncr, "global_buckling_RF": rf,
            }
            station_sweep.append(item)
            sweep.append(item)
        worst = min(station_sweep, key=lambda x: x["global_buckling_RF"])
        modes = {
            "global_shear_buckling": worst["global_buckling_RF"],
            "core_shear_H100_proxy": core_rf,
            "face_shear": face_shear_rf,
            "face_wrinkling_principal_compression": face_wrinkling_rf,
            "face_compression_principal": face_compression_rf,
        }
        governing_mode = min(modes, key=modes.get)
        governing_rf = modes[governing_mode]
        summary.append({
            "blade_span_m": r, "web": row["web"], "airfoil": row["airfoil"],
            "face_layers_each_side": active_layers,
            "web_height_m": h, "design_shear_total_N": total_v,
            "design_shear_per_web_N": web_v, "applied_Nxy_N_per_m": applied_nxy,
            "worst_a_over_h": worst["a_over_h"],
            "global_buckling_RF": worst["global_buckling_RF"],
            "core_shear_RF_H100_proxy": core_rf,
            "face_shear_RF": face_shear_rf,
            "face_wrinkling_RF": face_wrinkling_rf,
            "face_compression_RF": face_compression_rf,
            "governing_mode": governing_mode, "governing_RF": governing_rf,
            "status": "PASS" if governing_rf >= 1.0 else "FAIL",
        })
        demand.append({
            "blade_span_m": r, "web": row["web"], "required_core_shear_strength_MPa": core_tau / 1e6,
            "H100_proxy_strength_MPa": CORE_SHEAR_PA / 1e6,
            "source_note": "Sandia Table 5 omits foam strength; H100 is a conservative MAT-006 proxy",
        })
    return summary, sweep, demand


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def write_svg(path: Path, rows: list[dict[str, object]]) -> None:
    width, height = 1100, 620
    left, right, top, bottom = 90, 40, 45, 85
    plot_w, plot_h = width - left - right, height - top - bottom
    x_max, y_min, y_max = 61.5, 0.1, 100.0
    def sx(x): return left + plot_w * x / x_max
    def sy(y):
        y = min(y_max, max(y_min, y))
        return top + plot_h * (np.log10(y_max) - np.log10(y)) / (np.log10(y_max) - np.log10(y_min))
    colors = {"forward": "#d94b2b", "aft": "#2577b9"}
    parts = [f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}">',
             '<rect width="100%" height="100%" fill="white"/>',
             '<text x="550" y="27" text-anchor="middle" font-family="Arial" font-size="20" font-weight="bold">Sandwich shear-web reserve factor along span</text>']
    for y in (0.1, 1, 10, 100):
        yy = sy(y)
        parts.append(f'<line x1="{left}" y1="{yy}" x2="{width-right}" y2="{yy}" stroke="#d0d5dc"/>')
        parts.append(f'<text x="{left-12}" y="{yy+5}" text-anchor="end" font-family="Arial" font-size="13">{y:g}</text>')
    parts.append(f'<line x1="{left}" y1="{sy(1)}" x2="{width-right}" y2="{sy(1)}" stroke="#111" stroke-width="2" stroke-dasharray="7,5"/>')
    for web in ("forward", "aft"):
        subset = sorted((r for r in rows if r["web"] == web), key=lambda r: r["blade_span_m"])
        pts = " ".join(f'{sx(float(r["blade_span_m"])):.1f},{sy(float(r["governing_RF"])):.1f}' for r in subset)
        parts.append(f'<polyline points="{pts}" fill="none" stroke="{colors[web]}" stroke-width="4"/>')
        for r in subset:
            parts.append(f'<circle cx="{sx(float(r["blade_span_m"])):.1f}" cy="{sy(float(r["governing_RF"])):.1f}" r="4" fill="{colors[web]}"/>')
    parts += [f'<text x="{left+plot_w/2}" y="{height-25}" text-anchor="middle" font-family="Arial" font-size="16">Blade span (m)</text>',
              f'<text transform="translate(25 {top+plot_h/2}) rotate(-90)" text-anchor="middle" font-family="Arial" font-size="16">Governing RF (log scale)</text>',
              f'<line x1="{width-260}" y1="55" x2="{width-220}" y2="55" stroke="{colors["forward"]}" stroke-width="4"/><text x="{width-210}" y="60" font-family="Arial" font-size="14">forward web</text>',
              f'<line x1="{width-260}" y1="78" x2="{width-220}" y2="78" stroke="{colors["aft"]}" stroke-width="4"/><text x="{width-210}" y="83" font-family="Arial" font-size="14">aft web</text>',
              '</svg>']
    path.write_text("\n".join(parts), encoding="utf-8")


def main():
    summary, sweep, demand = assess()
    improved, improved_sweep, improved_demand = assess(3, (10.25, 38.95))
    comparison = ([{"variant": "Sandia_2DB", **row} for row in summary]
                  + [{"variant": "CAD_reinforced_3DB_midspan", **row} for row in improved])
    write_svg(SESSION_ROOT / "figures" / "nrel5mw_sandwich_web_rf.svg", improved)
    governing = min(summary, key=lambda row: row["governing_RF"])
    improved_governing = min(improved, key=lambda row: row["governing_RF"])
    print("Governing web: {web} at r={blade_span_m:.4f} m, {governing_mode}, RF={governing_RF:.3f}, {status}".format(**governing))
    print("Reinforced: {web} at r={blade_span_m:.4f} m, {governing_mode}, RF={governing_RF:.3f}, {status}".format(**improved_governing))


if __name__ == "__main__":
    main()
